### ISSUE TITLE
Phaser and PIXI Export broken - Online editor

### ISSUE THREAD

**Issue by chrismckenna95** [Ezelia/EPSy#5]
The option to export into Phaser and PIXI are broken in the online editor.  
The console comes back with this log  - EPSYEDITOR.min.js:12 Uncaught Error: Corrupted zip : can't find end of central directory.
Other exports and imports work fine.

**Comment by alaa-eddine** [comment]
Just tested and it's working fine.

what browser are you using ? have you tested on both Firefox and Chrome ?

**Comment by chrismckenna95** [comment]
Just tested on both Firefox and Chrome - 
![console](https://cloud.githubusercontent.com/assets/5185559/6802665/244a7fb6-d22a-11e4-805f-685dd249db3b.JPG)

**Comment by alaa-eddine** [comment]
you're right there is something wrong with the export function ... I made a mistake in the last update. I'll fix that ASAP.
Thank you for reporting

**Comment by alaa-eddine** [comment]
if you need the export before I make the fix : 
you can download this file http://labs.ezelia.com/epsy/EPSy-phaser-export2.zip 
extract it.
edit index.html 
and replace value of _data variable with the content from EPSy Editor export (menu > Export config)

**Comment by alaa-eddine** [comment]
it's fixed now, can you check please ?

**Comment by chrismckenna95** [comment]
Exports working fine now.
