### ISSUE TITLE
Does not work with the latest Phaser lib

### ISSUE THREAD

**Issue by Valentine1** [Ezelia/EPSy#7]
when linked to the Phaser v2.5 lib not particles are displayed, the same code works fine with v.2.0.6

**Comment by babruix** [comment]
Confirming, latest working version of Phaser is 2.5.0

**Comment by babruix** [comment]
I have created pull request with the fix:
https://github.com/Ezelia/EPSy/pull/8

Attached patched library also...
[EPSY.Phaser.js.zip](https://github.com/Ezelia/EPSy/files/532158/EPSY.Phaser.js.zip)

**Comment by alaa-eddine** [comment]
the solution proposed by @babruix works fine, and have been merged :) 
if you are using the online editor, please replace the phaser plugin with the one from this repository.

I need to find the online editor source code and upload it to github too ...
